// 多语言配置
const LANGUAGE_CONFIG = {
    // 默认语言
    defaultLanguage: 'zh',

    // 支持的语言列表
    supportedLanguages: [
        { code: 'zh', name: '中文' },
        { code: 'ru', name: 'Русский' },
        { code: 'en', name: 'English' },
        { code: 'ja', name: '日本語' }
    ],

    // 翻译文本
    translations: {
        zh: {
            title: "更好的Wplace颜色转换器",
            selectPalette: "1. 选择调色板",
            freePalette: "免费调色板",
            paidPalette: "付费调色板",
            selectAll: "全选",
            deselectAll: "取消全选",
            uploadImage: "2. 上传图片",
            clickOrDrag: "点击或拖拽图片",
            adjustParams: "3. 调整参数",
            ditherStrength: "抖动强度",
            imageSize: "图片尺寸",
            width: "宽",
            height: "高",
            totalPixels: "总像素",
            selectAlgorithm: "4. 选择算法",
            colorStats: "图像颜色统计",
            processImageFirst: "处理图片后在此显示颜色用量。",
            uploadImageFirst: "请先上传一张图片",
            zoom: "缩放",
            downloadCurrent: "下载当前效果图",
            noColorsDetected: "未在图像中检测到已选颜色。",
            footerSource: "源码来自",
            footerThanks: "感谢【P.R.T.S Alliance】Discord群组",
            footerCustom: "由【三文鱼、肉意思】制作",
            enableColorPicker: "启用颜色选择模式",
            selectedColor: "已选择颜色",
            replacementColor: "替换颜色",
            freeColors: "免费颜色",
            paidColors: "付费颜色",
            applyReplacement: "应用替换",
            clearSelection: "清除选择",
            resetAllReplacements: "重置所有替换",
            currentReplacements: "当前替换映射",
            noReplacements: "暂无颜色替换",
            remove: "删除",
            clickImageToSelectColor: "点击图像选择颜色",
            // 实验性图片处理功能
            imageProcessing: "图片处理（实验性）",
            brightness: "亮度",
            contrast: "对比度",
            saturation: "饱和度",
            resetAdjustments: "重置所有调整",
            imageProcessingDesc: "调整图片的亮度、对比度和饱和度"
        },
        ru: {
            title: "Лучший конвертер цветов Wplace",
            selectPalette: "1. Выберите палитру",
            freePalette: "Бесплатная палитра",
            paidPalette: "Платная палитра",
            selectAll: "Выбрать все",
            deselectAll: "Отменить выбор",
            uploadImage: "2. Загрузить изображение",
            clickOrDrag: "Нажмите или перетащите изображение",
            adjustParams: "3. Настроить параметры",
            ditherStrength: "Сила дизеринга",
            imageSize: "Размер изображения",
            width: "Ширина",
            height: "Высота",
            totalPixels: "Всего пикселей",
            selectAlgorithm: "4. Выберите алгоритм",
            colorStats: "Статистика цветов изображения",
            processImageFirst: "Статистика цветов будет показана после обработки изображения.",
            uploadImageFirst: "Пожалуйста, сначала загрузите изображение",
            zoom: "Масштаб",
            downloadCurrent: "Скачать текущий результат",
            noColorsDetected: "В изображении не обнаружено выбранных цветов.",
            footerSource: "Исходный код из",
            footerThanks: "Спасибо группе【P.R.T.S Alliance】Discord",
            footerCustom: "由【三文鱼、肉意思】制作",
            enableColorPicker: "Включить режим выбора цвета",
            selectedColor: "Выбранный цвет",
            replacementColor: "Цвет замены",
            freeColors: "Бесплатные цвета",
            paidColors: "Платные цвета",
            applyReplacement: "Применить замену",
            clearSelection: "Очистить выбор",
            resetAllReplacements: "Сбросить все замены",
            currentReplacements: "Текущие замены",
            noReplacements: "Нет замен цветов",
            remove: "Удалить",
            clickImageToSelectColor: "Нажмите на изображение для выбора цвета",
            // 实验性图片处理功能
            imageProcessing: "Обработка изображения (экспериментально)",
            brightness: "Яркость",
            contrast: "Контрастность",
            saturation: "Насыщенность",
            resetAdjustments: "Сбросить все настройки",
            imageProcessingDesc: "Настройте яркость, контрастность и насыщенность изображения"
        },
        en: {
            title: "Better Wplace Color Converter",
            selectPalette: "1. Select Palette",
            freePalette: "Free Palette",
            paidPalette: "Paid Palette",
            selectAll: "Select All",
            deselectAll: "Deselect All",
            uploadImage: "2. Upload Image",
            clickOrDrag: "Click or drag image",
            adjustParams: "3. Adjust Parameters",
            ditherStrength: "Dither Strength",
            imageSize: "Image Size",
            width: "Width",
            height: "Height",
            totalPixels: "Total Pixels",
            selectAlgorithm: "4. Select Algorithm",
            colorStats: "Image Color Statistics",
            processImageFirst: "Color usage will be displayed after processing the image.",
            uploadImageFirst: "Please upload an image first",
            zoom: "Zoom",
            downloadCurrent: "Download Current Result",
            noColorsDetected: "No selected colors detected in the image.",
            footerSource: "Source code from",
            footerThanks: "Thanks to【P.R.T.S Alliance】Discord group",
            footerCustom: "由【三文鱼、肉意思】制作",
            enableColorPicker: "Enable Color Picker Mode",
            selectedColor: "Selected Color",
            replacementColor: "Replacement Color",
            freeColors: "Free Colors",
            paidColors: "Paid Colors",
            applyReplacement: "Apply Replacement",
            clearSelection: "Clear Selection",
            resetAllReplacements: "Reset All Replacements",
            currentReplacements: "Current Replacements",
            noReplacements: "No color replacements",
            remove: "Remove",
            clickImageToSelectColor: "Click image to select color",
            // 实验性图片处理功能
            imageProcessing: "Image Processing (Experimental)",
            brightness: "Brightness",
            contrast: "Contrast",
            saturation: "Saturation",
            resetAdjustments: "Reset All Adjustments",
            imageProcessingDesc: "Adjust brightness, contrast and saturation of the image"
        },
        ja: {
            title: "より良いWplace色変換器",
            selectPalette: "1. パレットを選択",
            freePalette: "無料パレット",
            paidPalette: "有料パレット",
            selectAll: "すべて選択",
            deselectAll: "選択解除",
            uploadImage: "2. 画像をアップロード",
            clickOrDrag: "画像をクリックまたはドラッグ",
            adjustParams: "3. パラメータを調整",
            ditherStrength: "ディザ強度",
            imageSize: "画像サイズ",
            width: "幅",
            height: "高さ",
            totalPixels: "総ピクセル数",
            selectAlgorithm: "4. アルゴリズムを選択",
            colorStats: "画像色統計",
            processImageFirst: "画像処理後に色の使用量が表示されます。",
            uploadImageFirst: "まず画像をアップロードしてください",
            zoom: "ズーム",
            downloadCurrent: "現在の結果をダウンロード",
            noColorsDetected: "画像で選択された色が検出されませんでした。",
            footerSource: "ソースコードは",
            footerThanks: "【P.R.T.S Alliance】Discordグループに感謝",
            footerCustom: "由【三文鱼、肉意思】制作",
            enableColorPicker: "カラーピッカーモードを有効にする",
            selectedColor: "選択した色",
            replacementColor: "置換色",
            freeColors: "無料の色",
            paidColors: "有料の色",
            applyReplacement: "置換を適用",
            clearSelection: "選択をクリア",
            resetAllReplacements: "すべての置換をリセット",
            currentReplacements: "現在の置換マッピング",
            noReplacements: "色の置換はありません",
            remove: "削除",
            clickImageToSelectColor: "画像をクリックして色を選択",
            // 实验性图片处理功能
            imageProcessing: "画像処理（実験的）",
            brightness: "明るさ",
            contrast: "コントラスト",
            saturation: "彩度",
            resetAdjustments: "すべての調整をリセット",
            imageProcessingDesc: "画像の明るさ、コントラスト、彩度を調整します"
        }
    }
};
