// 多语言配置
const LANGUAGE_CONFIG = {
    // 默认语言
    defaultLanguage: 'zh',

    // 支持的语言列表
    supportedLanguages: [
        { code: 'zh', name: '中文' },
        { code: 'ru', name: 'Русский' },
        { code: 'en', name: 'English' },
        { code: 'ja', name: '日本語' }
    ],

    // 翻译文本
    translations: {
        zh: {
            title: "更好的Wplace颜色转换器",
            selectPalette: "1. 选择调色板",
            freePalette: "免费调色板",
            paidPalette: "付费调色板",
            selectAll: "全选",
            deselectAll: "取消全选",
            uploadImage: "2. 上传图片",
            clickOrDrag: "点击或拖拽图片",
            adjustParams: "3. 调整参数",
            ditherStrength: "抖动强度",
            imageSize: "图片尺寸",
            width: "宽",
            height: "高",
            totalPixels: "总像素",
            selectAlgorithm: "4. 选择算法",
            colorStats: "图像颜色统计",
            processImageFirst: "处理图片后在此显示颜色用量。",
            uploadImageFirst: "请先上传一张图片",
            zoom: "缩放",
            downloadCurrent: "下载当前效果图",
            noColorsDetected: "未在图像中检测到已选颜色。",
            footerSource: "源码来自",
            footerThanks: "感谢【P.R.T.S Alliance】Discord群组",
            footerCustom: "原网页由【三文鱼、肉意思】制作、现由【和平之师】魔改",
            enableColorPicker: "启用颜色选择模式",
            selectedColor: "已选择颜色",
            replacementColor: "替换颜色",
            freeColors: "免费颜色",
            paidColors: "付费颜色",
            applyReplacement: "应用替换",
            clearSelection: "清除选择",
            resetAllReplacements: "重置所有替换",
            currentReplacements: "当前替换映射",
            noReplacements: "暂无颜色替换",
            remove: "删除",
            clickImageToSelectColor: "点击图像选择颜色",
            // 实验性图片处理功能
            imageProcessing: "图片处理（实验性）",
            brightness: "亮度",
            contrast: "对比度",
            saturation: "饱和度",
            sharpness: "锐化",
            hue: "色相",
            temperature: "色温",
            resetAdjustments: "重置所有调整",
            imageProcessingDesc: "调整图片的亮度、对比度、饱和度、锐化、色相和色温",
            // 实时调整开关
            realtimeToggle: "开启实时调整",
            manualGenerateBtn: "生成图片",
            // 强制去除半透明像素
            forceOpaqueToggle: "强制去除半透明像素",
            forceOpaqueDesc: "开启后：透明度<50%变透明，>=50%变不透明并匹配色板",
            // 预计完成时间
            participantCount: "参与人数",
            estimatedTime: "预计时间",
            // 颜色选择与替换
            lockColors: "锁定颜色",
            colorSelection: "5. 颜色选择与替换",
            notSelected: "未选择",
            // 其他UI元素
            ditherScale: "抖动倍率",
            imageProcessingDesc: "调整图片的亮度、对比度和饱和度",
            exportSelection: "导出选区",
            editInPainter: "在绘画工具中编辑",
            pixelPaintTool: "像素绘画工具",
            transparentColor: "透明"
        },
        ru: {
            title: "Лучший конвертер цветов Wplace",
            selectPalette: "1. Выберите палитру",
            freePalette: "Бесплатная палитра",
            paidPalette: "Платная палитра",
            selectAll: "Выбрать все",
            deselectAll: "Отменить выбор",
            uploadImage: "2. Загрузить изображение",
            clickOrDrag: "Нажмите или перетащите изображение",
            adjustParams: "3. Настроить параметры",
            ditherStrength: "Сила дизеринга",
            imageSize: "Размер изображения",
            width: "Ширина",
            height: "Высота",
            totalPixels: "Всего пикселей",
            selectAlgorithm: "4. Выберите алгоритм",
            colorStats: "Статистика цветов изображения",
            processImageFirst: "Статистика цветов будет показана после обработки изображения.",
            uploadImageFirst: "Пожалуйста, сначала загрузите изображение",
            zoom: "Масштаб",
            downloadCurrent: "Скачать текущий результат",
            noColorsDetected: "В изображении не обнаружено выбранных цветов.",
            footerSource: "Исходный код из",
            footerThanks: "Спасибо группе【P.R.T.S Alliance】Discord",
            footerCustom: "原网页由【三文鱼、肉意思】制作、现由【和平之师】魔改",
            enableColorPicker: "Включить режим выбора цвета",
            selectedColor: "Выбранный цвет",
            replacementColor: "Цвет замены",
            freeColors: "Бесплатные цвета",
            paidColors: "Платные цвета",
            applyReplacement: "Применить замену",
            clearSelection: "Очистить выбор",
            resetAllReplacements: "Сбросить все замены",
            currentReplacements: "Текущие замены",
            noReplacements: "Нет замен цветов",
            remove: "Удалить",
            clickImageToSelectColor: "Нажмите на изображение для выбора цвета",
            // 实验性图片处理功能
            imageProcessing: "Обработка изображения (экспериментально)",
            brightness: "Яркость",
            contrast: "Контрастность",
            saturation: "Насыщенность",
            sharpness: "Резкость",
            hue: "Оттенок",
            temperature: "Цветовая температура",
            resetAdjustments: "Сбросить все настройки",
            imageProcessingDesc: "Настройте яркость, контрастность, насыщенность, резкость, оттенок и цветовую температуру изображения",
            // 实时调整开关
            realtimeToggle: "Включить реальное время",
            manualGenerateBtn: "Сгенерировать изображение",
            // 强制去除半透明像素
            forceOpaqueToggle: "Принудительно удалить полупрозрачные пиксели",
            forceOpaqueDesc: "Вкл: прозрачность <50% станет прозрачной, >=50% станет непрозрачной",
            // 预计完成时间
            participantCount: "Участников",
            estimatedTime: "Расчетное время",
            // 颜色选择与替换
            lockColors: "Блокировать цвета",
            colorSelection: "5. Выбор и замена цветов",
            notSelected: "Не выбрано",
            // 其他UI元素
            ditherScale: "Масштаб дизеринга",
            exportSelection: "Экспортировать выделение",
            editInPainter: "Редактировать в инструменте рисования",
            pixelPaintTool: "Инструмент пиксельной живописи",
            transparentColor: "Прозрачный"
        },
        en: {
            title: "Better Wplace Color Converter",
            selectPalette: "1. Select Palette",
            freePalette: "Free Palette",
            paidPalette: "Paid Palette",
            selectAll: "Select All",
            deselectAll: "Deselect All",
            uploadImage: "2. Upload Image",
            clickOrDrag: "Click or drag image",
            adjustParams: "3. Adjust Parameters",
            ditherStrength: "Dither Strength",
            imageSize: "Image Size",
            width: "Width",
            height: "Height",
            totalPixels: "Total Pixels",
            selectAlgorithm: "4. Select Algorithm",
            colorStats: "Image Color Statistics",
            processImageFirst: "Color usage will be displayed after processing the image.",
            uploadImageFirst: "Please upload an image first",
            zoom: "Zoom",
            downloadCurrent: "Download Current Result",
            noColorsDetected: "No selected colors detected in the image.",
            footerSource: "Source code from",
            footerThanks: "Thanks to【P.R.T.S Alliance】Discord group",
            footerCustom: "原网页由【三文鱼、肉意思】制作、现由【和平之师】魔改",
            enableColorPicker: "Enable Color Picker Mode",
            selectedColor: "Selected Color",
            replacementColor: "Replacement Color",
            freeColors: "Free Colors",
            paidColors: "Paid Colors",
            applyReplacement: "Apply Replacement",
            clearSelection: "Clear Selection",
            resetAllReplacements: "Reset All Replacements",
            currentReplacements: "Current Replacements",
            noReplacements: "No color replacements",
            remove: "Remove",
            clickImageToSelectColor: "Click image to select color",
            // 实验性图片处理功能
            imageProcessing: "Image Processing (Experimental)",
            brightness: "Brightness",
            contrast: "Contrast",
            saturation: "Saturation",
            sharpness: "Sharpness",
            hue: "Hue",
            temperature: "Color Temperature",
            resetAdjustments: "Reset All Adjustments",
            imageProcessingDesc: "Adjust brightness, contrast, saturation, sharpness, hue and color temperature of the image",
            // 实时调整开关
            realtimeToggle: "Enable Real-time Adjustment",
            manualGenerateBtn: "Generate Image",
            // 强制去除半透明像素
            forceOpaqueToggle: "Force Remove Semi-transparent Pixels",
            forceOpaqueDesc: "On: opacity <50% becomes transparent, >=50% becomes opaque",
            // 预计完成时间
            participantCount: "Participants",
            estimatedTime: "Estimated Time",
            // 颜色选择与替换
            lockColors: "Lock Colors",
            colorSelection: "5. Color Selection and Replacement",
            notSelected: "Not Selected",
            // 其他UI元素
            ditherScale: "Dither Scale",
            imageProcessingDesc: "Adjust brightness, contrast, saturation, sharpness, hue and color temperature of the image",
            exportSelection: "Export Selection",
            editInPainter: "Edit in Painting Tool",
            pixelPaintTool: "Pixel Paint Tool",
            transparentColor: "Transparent"
        },
        ja: {
            title: "より良いWplace色変換器",
            selectPalette: "1. パレットを選択",
            freePalette: "無料パレット",
            paidPalette: "有料パレット",
            selectAll: "すべて選択",
            deselectAll: "選択解除",
            uploadImage: "2. 画像をアップロード",
            clickOrDrag: "画像をクリックまたはドラッグ",
            adjustParams: "3. パラメータを調整",
            ditherStrength: "ディザ強度",
            imageSize: "画像サイズ",
            width: "幅",
            height: "高さ",
            totalPixels: "総ピクセル数",
            selectAlgorithm: "4. アルゴリズムを選択",
            colorStats: "画像色統計",
            processImageFirst: "画像処理後に色の使用量が表示されます。",
            uploadImageFirst: "まず画像をアップロードしてください",
            zoom: "ズーム",
            downloadCurrent: "現在の結果をダウンロード",
            noColorsDetected: "画像で選択された色が検出されませんでした。",
            footerSource: "ソースコードは",
            footerThanks: "【P.R.T.S Alliance】Discordグループに感謝",
            footerCustom: "原网页由【三文鱼、肉意思】制作、现由【和平之师】魔改",
            enableColorPicker: "カラーピッカーモードを有効にする",
            selectedColor: "選択した色",
            replacementColor: "置換色",
            freeColors: "無料の色",
            paidColors: "有料の色",
            applyReplacement: "置換を適用",
            clearSelection: "選択をクリア",
            resetAllReplacements: "すべての置換をリセット",
            currentReplacements: "現在の置換マッピング",
            noReplacements: "色の置換はありません",
            remove: "削除",
            clickImageToSelectColor: "画像をクリックして色を選択",
            // 实验性图片处理功能
            imageProcessing: "画像処理（実験的）",
            brightness: "明るさ",
            contrast: "コントラスト",
            saturation: "彩度",
            sharpness: "シャープネス",
            hue: "色相",
            temperature: "色温度",
            resetAdjustments: "すべての調整をリセット",
            imageProcessingDesc: "画像の明るさ、コントラスト、彩度、シャープネス、色相、色温度を調整します",
            // 实时调整开关
            realtimeToggle: "リアルタイム調整を有効にする",
            manualGenerateBtn: "画像を生成",
            // 强制去除半透明像素
            forceOpaqueToggle: "半透明ピクセルを強制削除",
            forceOpaqueDesc: "オン: 透明度<50%は透明に、>=50%は不透明になります",
            // 预计完成时间
            participantCount: "参加者数",
            estimatedTime: "予想時間",
            // 颜色选择与替换
            lockColors: "色をロック",
            colorSelection: "5. 色の選択と置換",
            notSelected: "未選択",
            // 其他UI元素
            ditherScale: "ディザ倍率",
            exportSelection: "選択範囲をエクスポート",
            editInPainter: "描画ツールで編集",
            pixelPaintTool: "ピクセルペイントツール",
            transparentColor: "透明"
        }
    }
};
